### ISSUE TITLE
Crash on Nokia1

### ISSUE THREAD

**Issue by ligi** [slockit/in3-example-android#2]
as discussed with @simon-jentzsch yesterday - found a way to make the crash reproducible - it always happens on a Nokia One. 
It works on the emulator (x86) and Motorola Vision. Will try to test more devices later. 
```
01-16 02:06:43.409 7396-7396/com.example.incubed E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.ExceptionInInitializerError
        at com.example.incubed.MainActivity$in3$2.invoke(MainActivity.kt:48)
        at com.example.incubed.MainActivity$in3$2.invoke(MainActivity.kt:46)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.example.incubed.MainActivity.getIn3(MainActivity.kt)
        at com.example.incubed.MainActivity$onCreate$1$1$1.invokeSuspend(MainActivity.kt:56)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
     Caused by: java.lang.RuntimeException: Could not load the library for /in3/native/libin3_jni_arm.so
        at in3.Loader.loadLibrary(Loader.java:100)
        at in3.IN3.<clinit>(IN3.java:278)
        at com.example.incubed.MainActivity$in3$2.invoke(MainActivity.kt:48) 
        at com.example.incubed.MainActivity$in3$2.invoke(MainActivity.kt:46) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at com.example.incubed.MainActivity.getIn3(MainActivity.kt) 
        at com.example.incubed.MainActivity$onCreate$1$1$1.invokeSuspend(MainActivity.kt:56) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742) 
```

**Comment by ligi** [comment]
Perhaps this helps:
![image](https://user-images.githubusercontent.com/111600/72484790-d6535980-3805-11ea-8003-e276dee309c2.png)

**Comment by ligi** [comment]
interestingly replacing:

`System.loadLibrary(getLibName());`

with 

`System.load("/data/data/com.example.incubed/lib/libin3_jni.so");`

let's me load the lib

**Comment by simon-jentzsch** [comment]
we are currently trying to reproduce it, but I think we will need to change the way the Loader finds the library. Because currently we try to load the library with `System.loadLibrary()` first. if this does not work we select and load a precompiled library embedded. In this example, we don't embeded anything.

**Comment by simon-jentzsch** [comment]
this has been fixed. As the next release ( in the next days) will contain the bugfix.

**Comment by ligi** [comment]
YAY - thanks!
